"""
Text-to-Speech generator using Gemini's multi-speaker TTS API.

Each :class:`~tldr.llm_summarizer.DialogueChunk` is converted into raw PCM
audio bytes (24 kHz, mono, 16-bit signed little-endian) by calling the
configured Gemini TTS model with a :class:`~google.genai.types.MultiSpeakerVoiceConfig`.

A natural-language audio profile preamble is prepended to each chunk before
sending to the TTS API.  This preamble defines each host's personality,
the scene context, and director's notes so that Gemini TTS interprets inline
emotional cues (e.g. "(avec enthousiasme)") generated by the LLM with the
right character voices.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

import coloredlogs
from google import genai
from google.genai import types

from tldr.retry import gemini_retry

if TYPE_CHECKING:
    from tldr.llm_summarizer import DialogueChunk

logger = logging.getLogger(__name__)
coloredlogs.install(level="DEBUG", logger=logger)


def _build_tts_prompt(chunk_text: str, gemini_cfg: dict) -> str:
    """
    Prepend a natural-language audio profile preamble to a dialogue chunk.

    The preamble instructs Gemini TTS to apply consistent speaker personalities
    and honour inline emotional cues written in parentheses within the dialogue.

    Parameters
    ----------
    chunk_text : str
        The raw dialogue text for this chunk (e.g. "Alex: (avec enthousiasme) ...").
    gemini_cfg : dict
        Resolved Gemini configuration section.  Uses ``speaker1``, ``speaker2``
        (each with ``name`` and optional ``personality`` keys), an optional
        ``tts_style.scene`` string, and an optional ``tts_style.pace`` string
        that provides a natural-language description of the desired speaking pace
        (e.g. ``"slow and deliberate"``).  When absent, defaults to ``"natural"``.

    Returns
    -------
    str
        The preamble followed by the dialogue text, ready for the TTS API.
    """
    s1 = gemini_cfg["speaker1"]
    s2 = gemini_cfg["speaker2"]
    tts_style = gemini_cfg.get("tts_style", {})
    scene = tts_style.get("scene", "")
    pace = tts_style.get("pace", "natural")

    s1_personality = s1.get("personality", "enthusiastic and curious")
    s2_personality = s2.get("personality", "analytical and thoughtful")

    preamble = (
        f"Audio profile: Two hosts of a French tech podcast, speaking in French.\n"
        f"{s1['name']} is {s1_personality}.\n"
        f"{s2['name']} is {s2_personality}.\n"
    )
    if scene:
        preamble += f"Scene: {scene}\n"
    preamble += (
        f"Director's notes: Conversational pace — {pace}; speak clearly, "
        "allow a natural beat between sentences so the listener can absorb each idea. "
        "Genuine reactions, honour any emotional cues written in parentheses in the dialogue.\n\n"
    )
    return preamble + chunk_text


def generate_audio_chunks(
    chunks: list[DialogueChunk],
    gemini_cfg: dict,
) -> list[bytes]:
    """
    Convert a list of dialogue chunks into raw PCM audio bytes using Gemini TTS.

    Each chunk is sent as a separate TTS request so that the 4 000-byte text
    limit is respected.  A natural-language audio profile preamble is prepended
    to each chunk to give the TTS model personality and emotional context.
    The resulting audio data for each chunk is returned in the same order as
    the input.

    Parameters
    ----------
    chunks : list[DialogueChunk]
        Ordered dialogue chunks produced by :func:`~tldr.llm_summarizer.generate_dialogue`.
    gemini_cfg : dict
        Resolved Gemini configuration with keys:
        ``api_key``, ``tts_model``, ``speaker1`` ({``name``, ``voice``,
        ``personality``}), ``speaker2`` ({``name``, ``voice``, ``personality``}),
        and optional ``tts_style`` ({``scene``, ``temperature``}).

    Returns
    -------
    list[bytes]
        One PCM bytes object per input chunk, in the same order.
        Each bytes object is raw 24 kHz / mono / 16-bit signed little-endian audio.

    Raises
    ------
    RuntimeError
        If the Gemini API returns an unexpected response structure for a chunk.

    Examples
    --------
    >>> audio_chunks = generate_audio_chunks(dialogue_chunks, gemini_cfg)
    >>> len(audio_chunks) == len(dialogue_chunks)
    True
    """
    client = genai.Client(api_key=gemini_cfg["api_key"])

    speaker1_cfg = gemini_cfg["speaker1"]
    speaker2_cfg = gemini_cfg["speaker2"]
    temperature = gemini_cfg.get("tts_style", {}).get("temperature", 1.0)

    voice_config = types.MultiSpeakerVoiceConfig(
        speaker_voice_configs=[
            types.SpeakerVoiceConfig(
                speaker=speaker1_cfg["name"],
                voice_config=types.VoiceConfig(
                    prebuilt_voice_config=types.PrebuiltVoiceConfig(
                        voice_name=speaker1_cfg["voice"],
                    )
                ),
            ),
            types.SpeakerVoiceConfig(
                speaker=speaker2_cfg["name"],
                voice_config=types.VoiceConfig(
                    prebuilt_voice_config=types.PrebuiltVoiceConfig(
                        voice_name=speaker2_cfg["voice"],
                    )
                ),
            ),
        ]
    )

    audio_chunks: list[bytes] = []

    for chunk in chunks:
        tts_prompt = _build_tts_prompt(chunk.text, gemini_cfg)
        logger.debug(
            "Generating TTS audio for chunk %d (%d bytes of text, %d bytes with preamble)",
            chunk.index,
            len(chunk.text.encode("utf-8")),
            len(tts_prompt.encode("utf-8")),
        )

        @gemini_retry
        def _call_tts() -> bytes:
            response = client.models.generate_content(
                model=gemini_cfg["tts_model"],
                contents=tts_prompt,
                config=types.GenerateContentConfig(
                    response_modalities=["AUDIO"],
                    temperature=temperature,
                    speech_config=types.SpeechConfig(
                        multi_speaker_voice_config=voice_config,
                    ),
                ),
            )
            try:
                return response.candidates[0].content.parts[0].inline_data.data
            except (IndexError, AttributeError) as exc:
                raise RuntimeError(
                    f"Unexpected TTS response structure for chunk {chunk.index}: {exc}"
                ) from exc

        pcm_bytes: bytes = _call_tts()

        logger.info(
            "Chunk %d: received %d bytes of PCM audio",
            chunk.index,
            len(pcm_bytes),
        )
        audio_chunks.append(pcm_bytes)

    return audio_chunks
